/*
 * Appointment List Api
 *
 * Stomatology Appointment List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xdiscantiny@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package stomatology_al

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type StomatologyAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateStomatology - Saves new stomatology definition
   CreateStomatology(ctx *gin.Context)

    // DeleteStomatology - Deletes specific stomatology
   DeleteStomatology(ctx *gin.Context)

 }

 // partial implementation of StomatologyAPI - all functions must be implemented in add on files
type implStomatologyAPI struct {

}

func newStomatologyAPI() StomatologyAPI {
  return &implStomatologyAPI{}
}

func (this *implStomatologyAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/stomatology", this.CreateStomatology)
  routerGroup.Handle( http.MethodDelete, "/stomatology/:stomatologyId", this.DeleteStomatology)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateStomatology - Saves new stomatology definition
// func (this *implStomatologyAPI) CreateStomatology(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteStomatology - Deletes specific stomatology
// func (this *implStomatologyAPI) DeleteStomatology(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

