/*
 * Appointment List Api
 *
 * Stomatology Appointment List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xdiscantiny@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package stomatology_al

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type StomatologyAppointmentListAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateAppointmentListEntry - Saves new entry into appointment list
   CreateAppointmentListEntry(ctx *gin.Context)

    // DeleteAppointmentListEntry - Deletes specific appointment
   DeleteAppointmentListEntry(ctx *gin.Context)

    // GetAppointmentListEntries - Provides appointments list
   GetAppointmentListEntries(ctx *gin.Context)

    // UpdateAppointmentListEntry - Updates specific entry
   UpdateAppointmentListEntry(ctx *gin.Context)

 }

 // partial implementation of StomatologyAppointmentListAPI - all functions must be implemented in add on files
type implStomatologyAppointmentListAPI struct {

}

func newStomatologyAppointmentListAPI() StomatologyAppointmentListAPI {
  return &implStomatologyAppointmentListAPI{}
}

func (this *implStomatologyAppointmentListAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/appointment-list/:appointmentsDate/entries", this.CreateAppointmentListEntry)
  routerGroup.Handle( http.MethodDelete, "/appointment-list/:appointmentsDate/entries/:id", this.DeleteAppointmentListEntry)
  routerGroup.Handle( http.MethodGet, "/appointment-list/:appointmentsDate/entries", this.GetAppointmentListEntries)
  routerGroup.Handle( http.MethodPut, "/appointment-list/:appointmentsDate/entries/:id", this.UpdateAppointmentListEntry)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateAppointmentListEntry - Saves new entry into appointment list
// func (this *implStomatologyAppointmentListAPI) CreateAppointmentListEntry(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteAppointmentListEntry - Deletes specific appointment
// func (this *implStomatologyAppointmentListAPI) DeleteAppointmentListEntry(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetAppointmentListEntries - Provides appointments list
// func (this *implStomatologyAppointmentListAPI) GetAppointmentListEntries(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // UpdateAppointmentListEntry - Updates specific entry
// func (this *implStomatologyAppointmentListAPI) UpdateAppointmentListEntry(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

