/*
 * Appointment List Api
 *
 * Stomatology Appointment List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xdiscantiny@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stomatology_al

type AppointmentDescription struct {

	// Reason for the appointment
	ReasonForAppointment string `json:"reasonForAppointment"`

	// List of teeths related to the appointment
	Teeths []string `json:"teeths"`
}
