/*
 * Appointment List Api
 *
 * Stomatology Appointment List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xdiscantiny@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stomatology_al

type AppointmentListEntry struct {

	// Unique identifier for the appointment
	Id string `json:"id"`

	// Date and time of the appointment
	Date string `json:"date"`

	// Name of the patient
	Patient string `json:"patient"`

	// Full name of the patient
	Fullname string `json:"fullname"`

	// Duration of the appointment in HH:mm format
	Duration string `json:"duration"`

	// Shortcut for the day of the appointment
	DayShortcut string `json:"dayShortcut"`

	Description AppointmentDescription `json:"description"`
}
