openapi: 3.0.0
servers:
  - description: Cluster Endpoint
    url: /api
info:
  description: Stomatology Appointment List management for Web-In-Cloud system
  version: '1.0.0'
  title: Appointment List Api
  contact:
    email: xdiscantiny@stuba.sk
  license:
    name: CC BY 4.0
    url: 'https://creativecommons.org/licenses/by/4.0/'
tags:
  - name: stomatologyAppointmentList
    description: Stomatology Appoinment management List API
paths:
  '/appointment-list/{appointmentsDate}/entries':
    get:
      tags:
        - stomatologyAppointmentList
      summary: Provides appointments list
      operationId: getAppointmentListEntries
      description: By using appointmentsId you get list of entries in stomatology appointments list
      parameters:
        - in: path
          name: appointmentsDate
          description: pass the id of the particular stomatology
          schema:
            type: string
            format: date
            pattern: "^\\d{4}-\\d{2}-\\d{2}$"
            description: The date of the appointments in yyyy-mm-dd format
          required: true
      responses:
        '200':
          description: value of the appointments entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AppointmentListEntry'
              examples:
                response:
                  $ref: '#/components/examples/AppointmentListExamples'
        '404':
          description: Appointments error
    post:
      tags:
        - stomatologyAppointmentList
      summary: Saves new entry into appointment list
      operationId: createAppointmentListEntry
      description: Use this method to store new entry into the appointment list.
      parameters:
        - in: path
          name: appointmentsDate
          description: pass the id of the particular ambulance
          required: true
          schema:
            type: string
            format: date
            pattern: "^\\d{4}-\\d{2}-\\d{2}$"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointmentListEntry'
            examples:
              request-sample:
                $ref: '#/components/examples/AppointmentListExample'
        description: Appointment list entry to store
        required: true
      responses:
        '200':
          description: >-
            Value of the appointment list entry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentListEntry'
              examples:
                updated-response:
                  $ref: '#/components/examples/AppointmentListExample'
        '404':
          description: Cannot add new appointments to selected old date.
  '/appointment-list/{appointmentsDate}/entries/{id}':
    put:
      tags:
        - stomatologyAppointmentList
      summary: Updates specific entry
      operationId: updateAppointmentListEntry
      description: Use this method to update content of the appointment list entry.
      parameters:
        - in: path
          name: appointmentsDate
          description: pass the id of the particular ambulance
          required: true
          schema:
            type: string
            format: date
            pattern: "^\\d{4}-\\d{2}-\\d{2}$"
        - in: path
          name: id
          description: pass the id of the particular entry in the appointment list
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointmentListEntry'
            examples:
              request:
                $ref: '#/components/examples/AppointmentListExample'
        description: Appointment list entry to update
        required: true
      responses:
        '200':
          description: >-
            value of the appoinment list entry with updated values
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentListEntry'
              examples:
                response:
                  $ref: '#/components/examples/AppointmentListExample'
        '404':
          description: Cannopt update appointment date older than today
    delete:
      tags:
        - stomatologyAppointmentList
      summary: Deletes specific appointment
      operationId: deleteAppointmentListEntry
      description: Use this method to delete the specific entry from the appointment list.
      parameters:
        - in: path
          name: appointmentsDate
          description: pass the id of the particular ambulance
          required: true
          schema:
            type: string
            format: date
            pattern: "^\\d{4}-\\d{2}-\\d{2}$"
        - in: path
          name: id
          description: pass the id of the particular entry in the appointment list
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Item deleted
        '404':
          description: Cannopt delete appointment date older than today
components:
  schemas:
    AppointmentListEntry:
      type: object
      required: [id, date, patient, fullname, duration, dayShortcut, description]
      properties:
        id:
          type: string
          example: '0'
          description: Unique identifier for the appointment
        date:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
          example: '2024-04-23'
          description: Date and time of the appointment
        patient:
          type: string
          example: 'Marrtin G.'
          description: Name of the patient
        fullname:
          type: string
          example: 'Martin Groma'
          description: Full name of the patient
        duration:
          type: string
          example: '7:00'
          description: Duration of the appointment in HH:mm format
        dayShortcut:
          type: string
          example: 'Po'
          description: Shortcut for the day of the appointment
        description:
          $ref: '#/components/schemas/AppointmentDescription'
      example:
        $ref: '#/components/examples/AppointmentListExample'
    AppointmentDescription:
      type: object
      required: [reasonForAppointment, teeths]
      properties:
        reasonForAppointment:
          type: string
          example: 'Pravidelná kontrola'
          description: Reason for the appointment
        teeths:
          type: array
          items:
            type: string
          description: List of teeths related to the appointment
  examples:
    AppointmentListExamples:
      summary: Examples of appointments
      description: An example of multiple appointment objects
      value:
        - id: '0'
          date: '2024-04-29'
          patient: 'Marrtin G.'
          fullname: 'Marrtin G.'
          duration: '7:00'
          dayShortcut: 'Po'
          description:
            reasonForAppointment: 'Pravidelná kontrola'
            teeths: []
        - id: '1'
          date: '2024-04-29'
          patient: 'Adam R.'
          fullname: 'Adam R.'
          duration: '8:00'
          dayShortcut: 'Po'
          description:
            reasonForAppointment: 'Bolesť zubov'
            teeths: []
        - id: '2'
          date: '2024-04-23'
          patient: 'Rudolf S.'
          fullname: 'Rudolf S.'
          duration: '12:00'
          dayShortcut: 'St'
          description:
            reasonForAppointment: 'Čistenie zubov'
            teeths: []
        - id: '3'
          date: '2024-04-23'
          patient: 'Ján N.'
          fullname: 'Ján N.'
          duration: '9:00'
          dayShortcut: 'Po'
          description:
            reasonForAppointment: 'Krvácanie ďasien'
            teeths: []
        - id: '4'
          date: '2024-04-23'
          patient: 'Branislav P.'
          fullname: 'Branislav P.'
          duration: '14:00'
          dayShortcut: 'Pia'
          description:
            reasonForAppointment: 'Zlomený zub'
            teeths: []
    AppointmentListExample:
      summary: Example of an appointment - Branislav P.
      description: An example of an appointment object for Branislav P.
      value:
        id: '4'
        date: '2024-04-23'
        patient: 'Branislav P.'
        fullname: 'Branislav P.'
        duration: '14:00'
        dayShortcut: 'Pia'
        description:
          reasonForAppointment: 'Zlomený zub'
          teeths: []
